python_tests(name='common_lib_tests',
  dependencies=[
    'src/python/houzz/common:config_lib',
    'src/python/houzz/common/logger:logger_lib',
    'src/python/houzz/common/metric/client:metric_client',
    'src/python/houzz/common/yaml:yaml_lib',
  ],
  sources=['config_tests.py'],
)

python_tests(name='calendar_utils_tests',
  dependencies=[
    'src/python/houzz/common:calendar_utils_lib',
  ],
  sources=['calendar_utils_tests.py']
)
