python_library(
    name='pyeloqua_lib',
    sources=[
        'bulk.py',
        'error_handling.py',
        'forms.py',
        'pyeloqua.py',
        'system_fields.py',
    ],
    dependencies=[
    ]
)

