python_library(
    name="stacksampler",
    sources=[
        "stacksampler.py",
    ],
    dependencies=[
        ":werkzeug_req"
    ]
)

python_requirement_library(
    name="werkzeug_req", requirements=[
        python_requirement(name='Werkzeug', requirement='Werkzeug==1.0.1'),
    ]
)
